site_name: Professional development
theme:
  name: material

  primary: blue grey
  font:
    text: Poor Story
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/eye
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/eye-outline
        name: Switch to light mode

  accent: indigo

  features:
      - content.code.annotate
      - content.code.copy
      - content.tabs.link
      - header.autohide
      - announce.dismiss
      - navigation.footer
      - navigation.indexes
      - navigation.sections
      - navigation.tabs
      - navigation.top
      - navigation.tracking
      - search.highlight
      - search.share
      - search.suggest